#!/usr/bin/env zsh

# ZSH
ln -sf ~/dotfile/zsh/.zshrc ~/.zshrc
ln -sf ~/dotfile/zsh/.zsh_aliases ~/.zsh_aliases
ln -sf ~/dotfile/zsh/.zsh_exports ~/.zsh_exports
ln -sf ~/dotfile/zsh/.zsh_functions ~/.zsh_functions

# GIT
ln -sf ~/dotfile/git/.gitconfig ~/.gitconfig
ln -sf ~/dotfile/git/.gitignore_global ~/.gitignore_global

# SSH
ln -sf ~/dotfile/ssh/config ~/.ssh/config

# VIM
ln -sf ~/dotfile/vim/.vimrc ~/.vimrc
ln -sf ~/dotfile/vim/.viminfo ~/.viminfo
